#!/usr/bin/env python3
"""
Plots metrics from CSV files generated by main_single.

Usage:
    ./scripts/plot_single_metrics.py --series <LABEL>=<PATH_TO_CSV> [--series ...] [options]

Examples:
    ./scripts/plot_single_metrics.py --series "0.1=results/0.1.csv" --series "0.5=results/0.5.csv"

Options:
    --series FRACTION=PATH      Series spec in format FRACTION=PATH_TO_CSV. Can be repeated.
    --smooth-span N             Initial EMA span for smoothing (default: 15).
    --max-smooth-span N         Maximum smoothing span available on sliders (default: 200).
    --[no-]interactive-sliders  Enable/disable per-metric interactive smoothing sliders.
    --title TITLE               Optional plot title.
    --out PATH                  Optional output image path (e.g., results/single-metrics.png).
    --no-show                   Do not open an interactive matplotlib window.

Expected Output:
    Generates a multi-panel plot with subplots for 'step_size', 'relative_gap', 
    'max_regret', and 'mean_regret' across iterations.
    
    If run interactively (without --no-show), it opens a Matplotlib window containing 
    the plots along with vertical sliders on the left. These sliders allow you to 
    dynamically adjust the exponential moving average (EMA) smoothing for each metric.
    
    If --out is provided, the resulting figure is saved to the specified file path.
"""
import argparse
import csv
import math
import pathlib
from dataclasses import dataclass

import matplotlib.pyplot as plt
from matplotlib import colors as mcolors
from matplotlib.widgets import Slider


METRICS = [
    "step_size",
    #"obj_val",
    "relative_gap",
    "max_regret",
    "mean_regret",
]


@dataclass
class SeriesData:
    label: str
    csv_path: pathlib.Path
    iteration: list[int]
    values: dict[str, list[float]]


def parse_series_arg(series_arg: str) -> tuple[str, pathlib.Path]:
    if "=" not in series_arg:
        raise ValueError(
            f"Invalid --series value '{series_arg}'. Expected format: FRACTION=PATH"
        )
    label, path_str = series_arg.split("=", 1)
    label = label.strip()
    path = pathlib.Path(path_str.strip())
    if not label:
        raise ValueError(f"Invalid --series value '{series_arg}': empty fraction label")
    if not path.exists():
        raise FileNotFoundError(f"CSV file does not exist: {path}")
    return label, path


def read_metrics_csv(label: str, csv_path: pathlib.Path) -> SeriesData:
    required_columns = ["iteration", *METRICS]
    rows: list[tuple[int, dict[str, float]]] = []

    with csv_path.open("r", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")

        missing_columns = [c for c in required_columns if c not in reader.fieldnames]
        if missing_columns:
            raise ValueError(
                f"CSV is missing required columns {missing_columns}: {csv_path}"
            )

        for row in reader:
            it = int(row["iteration"])
            metric_values = {metric: float(row[metric]) for metric in METRICS}
            rows.append((it, metric_values))

    rows.sort(key=lambda x: x[0])
    iteration = [it for it, _ in rows]
    values = {metric: [v[metric] for _, v in rows] for metric in METRICS}

    return SeriesData(label=label, csv_path=csv_path, iteration=iteration, values=values)


def exponential_moving_average(values: list[float], span: int) -> list[float]:
    if not values:
        return []
    if span <= 1:
        return list(values)

    alpha = 2.0 / (span + 1.0)
    smoothed: list[float] = []
    prev: float | None = None
    for value in values:
        if math.isnan(value):
            smoothed.append(float("nan"))
            continue
        if prev is None:
            prev = value
        else:
            prev = alpha * value + (1.0 - alpha) * prev
        smoothed.append(prev)
    return smoothed


def plot_metrics(
    series_list: list[SeriesData],
    smooth_span: int,
    interactive_sliders: bool,
    max_smooth_span: int,
    title: str | None,
    out_path: pathlib.Path | None,
    show: bool,
) -> None:
    fig, axes = plt.subplots(nrows=len(METRICS), ncols=1, figsize=(12, 16), sharex=True)
    if len(METRICS) == 1:
        axes = [axes]

    cmap = plt.get_cmap("tab10")
    # Map user-facing regularization r in [0, 1] to EMA span in [1, max_smooth_span].
    def regularization_to_span(regularization: float) -> int:
        reg = min(1.0, max(0.0, regularization))
        return 1 + int(round((max_smooth_span - 1) * reg))

    initial_regularization = (max(1, min(max_smooth_span, smooth_span)) - 1) / max(
        1, (max_smooth_span - 1)
    )

    smooth_lines: dict[str, list[tuple[list[int], list[float], any]]] = {
        metric: [] for metric in METRICS
    }

    for idx, series in enumerate(series_list):
        base_color = mcolors.to_rgb(cmap(idx % 10))

        for axis, metric in zip(axes, METRICS):
            y = series.values[metric]
            if metric in ("relative_gap", "mean_regret", "max_regret"):
                y = [value if value > 0.0 else float("nan") for value in y]

            y_smooth = exponential_moving_average(y, regularization_to_span(initial_regularization))
            (smooth_line,) = axis.plot(
                series.iteration,
                y_smooth,
                color=base_color,
                linewidth=2.0,
                linestyle="-",
                alpha=0.9,
                label=series.label,
            )
            smooth_lines[metric].append((series.iteration, y, smooth_line))


    for axis, metric in zip(axes, METRICS):
        if metric in ("relative_gap", "mean_regret", "max_regret"):
            axis.set_yscale("log")
        axis.set_ylabel(metric)
        axis.grid(alpha=0.25)
        axis.legend(loc="best", fontsize=9)

    axes[-1].set_xlabel("iteration")

    if title:
        fig.suptitle(title)

    if interactive_sliders and show:
        # Reserve space on the left for per-axis sliders.
        fig.subplots_adjust(left=0.24)
        slider_x = 0.06
        slider_width = 0.04
        sliders = []

        for axis, metric in zip(axes, METRICS):
            bbox = axis.get_position()
            slider_ax = fig.add_axes([slider_x, bbox.y0, slider_width, bbox.height])
            slider_ax.set_facecolor("#f0f0f0")
            slider = Slider(
                ax=slider_ax,
                label=f"{metric}\nsmooth",
                valmin=0.0,
                valmax=1.0,
                valinit=initial_regularization,
                valstep=0.01,
                orientation="vertical",
            )
            slider_line = getattr(slider, "hline", None)
            if slider_line is None:
                slider_line = getattr(slider, "vline", None)
            if slider_line is not None:
                slider_line.set_color("#1f77b4")
                slider_line.set_linewidth(2.0)

            def _on_change(val: float, metric_name: str = metric) -> None:
                span = regularization_to_span(val)
                for x_vals, y_vals, line in smooth_lines[metric_name]:
                    line.set_data(x_vals, exponential_moving_average(y_vals, span))
                fig.canvas.draw_idle()

            slider.on_changed(_on_change)
            sliders.append(slider)
        fig.canvas.draw_idle()
    else:
        fig.tight_layout()

    if out_path is not None:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=180)
        print(f"Saved plot to: {out_path}")

    if show:
        plt.show()


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Plot main_single metrics CSVs for multiple max_relative_regret_fraction values. "
            "Provide one --series FRACTION=PATH per CSV."
        )
    )
    parser.add_argument(
        "--series",
        action="append",
        required=True,
        help="Series spec in format FRACTION=PATH_TO_CSV. Can be repeated.",
    )
    parser.add_argument(
        "--smooth-span",
        type=int,
        default=15,
        help="Initial EMA span for smoothing (used to initialize regularization sliders).",
    )
    parser.add_argument(
        "--max-smooth-span",
        type=int,
        default=200,
        help="Maximum smoothing span available on interactive sliders (default: 200).",
    )
    parser.add_argument(
        "--interactive-sliders",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Enable per-metric interactive smoothing sliders (default: enabled). Use --no-interactive-sliders to disable.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default=None,
        help="Optional plot title.",
    )
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=None,
        help="Optional output image path (e.g., results/single-metrics.png).",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Do not open an interactive window.",
    )
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    series_list: list[SeriesData] = []
    for series_arg in args.series:
        label, csv_path = parse_series_arg(series_arg)
        series_list.append(read_metrics_csv(label, csv_path))

    def sort_key(series: SeriesData):
        try:
            return float(series.label)
        except ValueError:
            return series.label

    series_list.sort(key=sort_key)

    plot_metrics(
        series_list=series_list,
        smooth_span=args.smooth_span,
        interactive_sliders=args.interactive_sliders,
        max_smooth_span=max(2, args.max_smooth_span),
        title=args.title,
        out_path=args.out,
        show=not args.no_show,
    )


if __name__ == "__main__":
    main()
